In [7]:
import numpy as np
from matplotlib import pyplot as plt

# function definitions

def load_data(fname):
    data = np.genfromtxt(fname, delimiter=',', dtype=str)

    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if data[i][j] == '?':
                data[i][j] = np.random.choice(['n','y'])
    
    return data



def entropy(X):
    probs = [np.mean(X == c) for c in set(X)]
    return np.sum(-p * np.log2(p) for p in probs)


def ID3(d, n, data):
    # you will probably need additional helper functions
    return tree

def compute_gain(S, i):
    
    return gain


def split_data(data, split):
    
    return training_set, test_set


def learning_curve(d, n, training_set, test_set):
    # you will probably need additional helper functions
    return plot


def entropy(S):
    S = np.array(S)
    S = S / S.sum()
    return -(np.dot(S, np.log(S)))

def condent(S, i):
    S = np.array(S)
    S = S / S.sum()
    return 

#drv.entropy_conditional([1,2,2,2], [1,1,2,2])

# main

data = load_data('house-votes-84.data')

data = [[ord(y[0]) / 1000 for y in x] for x in data]

from scipy import stats as stats
print(stats.entropy(data[20]))
print(entropy(data[20]))

numBins = 3  # number of bins in each dimension
data = np.random.randn(100000, 2)  # generate 100000 3-d random data points
jointProbs, edges = np.histogramdd(data, bins=numBins)
jointProbs /= jointProbs.sum()

print(jointProbs)

2.831591763828246
2.831591763828246
[[0.00223 0.03809 0.00378]
 [0.03915 0.70997 0.06691]
 [0.0065  0.12269 0.01068]]
